; Script generated by the HM NIS Edit Script Wizard.
;--------------------------------
;Include Modern UI

  !include "MUI2.nsh"

;--------------------------------

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "JFXtrasEnsemble"
!define VERSION "0.1"
!define PRODUCT_PUBLISHER "JFXtras.org"
!define PRODUCT_WEB_SITE "http://www.jfxtras.org"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
;!define MUI_FINISHPAGE_NOAUTOCLOSE
;!define MUI_UNFINISHPAGE_NOAUTOCLOSE

;Name and file
Name "JFXtrasEnsemble"
OutFile "dist\JFXtrasEnsembleSetup.exe"
;Default installation folder
InstallDir "$PROGRAMFILES\${PRODUCT_NAME}"
;Get installation folder from registry if available
InstallDirRegKey HKCU  "Software\${PRODUCT_NAME}" ""

; MUI Settings
!define MUI_ICON "artSrc\JFXtrasEnsemble.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\win-uninstall.ico"
!define MUI_WELCOMEPAGE_TITLE "Welcome to the installation of ${PRODUCT_NAME} ${VERSION}"
;!define MUI_WELCOMEFINISHPAGE_BITMAP ".\images\installer_welcome.bmp"
;!define MUI_UNWELCOMEFINISHPAGE_BITMAP ".\images\installer_welcome.bmp"
;!define MUI_HEADERIMAGE
;!define MUI_HEADERIMAGE_BITMAP "images\header.bmp"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!define MUI_LICENSEPAGE_CHECKBOX
;!define MUI_LICENSEPAGE_BUTTON
;!define MUI_LICENSEPAGE_RADIOBUTTONS

;!insertmacro MUI_PAGE_LICENSE "resources\license.rtf"

; Directory page
!insertmacro MUI_PAGE_DIRECTORY 

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES 
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\JFXtrasEnsemble.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Language files
;!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Section "Hauptgruppe" SEC01
; Install for all users (not only current user). 
; NOTE: This must be set in every section
  SetShellVarContext all
  SetOutPath "$INSTDIR"
;  SetOverwrite ifnewer
  File "dist\JFXtrasEnsemble.exe"
;  File "dist\SplashScreen.png"
  File "dist\Ensemble.jar"
  SetOutPath "$INSTDIR\lib"
  File "dist\lib\*.jar"
  SetOutPath "$INSTDIR\jre"
  File /r "dist\jre\*.*"
SectionEnd

Section -AdditionalIcons
  SetShellVarContext all
  SetOutPath "$INSTDIR"
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" "$INSTDIR\JFXtrasEnsemble.exe"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\JFXtrasEnsemble.exe"
  WriteINIStr "$SMPROGRAMS\${PRODUCT_NAME}\Website.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  ;Store installation folder
  WriteRegStr HKCU  "Software\${PRODUCT_NAME}" "" $INSTDIR
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\JFXtrasEnsemble.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


;Function un.onUninstSuccess
;  HideWindow
;  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) wurde erfolgreich deinstalliert."
;FunctionEnd
;
;Function un.onInit
;  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "M�chten Sie $(^Name) und alle seinen Komponenten deinstallieren?" IDYES +2
;  Abort
;FunctionEnd

Section Uninstall
  SetShellVarContext all
  Delete "$INSTDIR\JFXtrasEnsemble.exe"
;  Delete "$INSTDIR\SplashScreen.png"
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\Ensemble.jar"
  Delete "$INSTDIR\lib\*.jar"
  Delete "$INSTDIR\lib\*.log"
  Delete "$INSTDIR\*.log"
  RMDir  /r "$INSTDIR\jre"

  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Website.url"
  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk"

  RMDir "$SMPROGRAMS\${PRODUCT_NAME}"
  RMDir "$INSTDIR\lib"
  RMDir "$INSTDIR"
  RMDir ""
  
  DeleteRegKey /ifempty HKCU  "Software\${PRODUCT_NAME}"
  DeleteRegKey /ifempty ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" 

;  SetAutoClose true
SectionEnd
